### ISSUE TITLE
[issue] width, height 오류

### ISSUE THREAD

**Issue by jaesimin0903** [beautiful-source/vue3-kakao-maps-docs#84]
안녕하세요 싸피 12기 수강하고 있는 학생입니다! width, height 지정에 관해 질문이 있어 issue 드립니다.

### 문제
![image](https://github.com/user-attachments/assets/328a4712-b5fc-47cc-b72b-9a2f55635093)

- 라이브러리 소개 사이트에서는 컨트롤 속성에 40rem 혹은 다른 단위와 붙여쓴 값 (ex : 40vw, vh, ....) 입력시 작동이 되는 반면

![image](https://github.com/user-attachments/assets/f44630e8-6d25-4597-a4c9-c5c435c11a81)
![image](https://github.com/user-attachments/assets/c2f455f0-8454-463d-b84d-15013fb4d9a4)

- 코드에 다음과 같이 입력 시 type 오류를 출력합니다.

### 예상되는 이유
- width , height 속성 타입은 number, string 으로 지정되어있어 number 가 아닌 값은 오류를 띕니다.
- 소개 웹 사이트 내에서는 커스텀으로 지정되어 있을 가능성이 있다고 생각합니다.

### 질문
```
    const r = S(() => ({
      width: isFinite(+i.width) ? i.width + "px" : i.width,
      height: isFinite(+i.height) ? i.height + "px" : i.height
    }));
```

- 위 코드가 width, height 를 결정하는 코드라고 사료되고, 숫자이외의 값을 입력하면 입력한 값 그대로 width, height를 결정하는 것으로 예상됩니다.
- 제가 놓치고 있는 부분이있는것인지?
- 그게 아니라면, width, height 부분의 타입을 string 으로 한정하고, 속성값에 단위까지 작성하게 바꿔야할것 같습니다.

시간내어 읽어주셔서 감사합니다.

**Comment by LireEruel** [comment]
얘기해주셔서 감사합니다. 혹시 문제는 해결되셨을까요? 아니면 여전히 발생하는 문제인가요?
